### ISSUE TITLE
页面分配

### ISSUE THREAD

**Issue by Blindingend** [Veiasai/Xmap#1]
# Pages
* 选择建筑
* 起始页：选择建筑之后进入的页面
	* 当前建筑的list，后期会按照热度排列
	* 导航按钮
	* 添加按钮
	* 底栏
* 个人信息页面
	* 用户头像，用户名
	* tab1：用户创建的点位
	* tab2：用户创建的路线
* 查看路线页面（用户选中路线之后进入的页面详情查看页面）
	* 按次序显示不同种类的路线信息
* 选择路线页面，根据点位或路线名称搜索，选中想要的路线
* 创建路线信息填写界面，填写路线名称，可选择起终点位
* 创建路线页面

**Comment by Veiasai** [comment]
Veia: 创建路线页面  查看路线页面

**Comment by Veiasai** [comment]
Veia： 起始页查看组件
