### ISSUE TITLE
第一周工作总结

### ISSUE THREAD

**Issue by Veiasai** [Veiasai/Xmap#2]
随便说点什么。

**Comment by GIRVANAL** [comment]
点什么

**Comment by GIRVANAL** [comment]
第一周过得很快，刚开始的时间有一些技术上的问题闹了笑话，后面熟悉了之后稍微有一些改善。因为负责后端的部分，要提供接口，虽然还是生产力还是很弱，但是起码改善了不少。第二周加油！！

**Comment by Blindingend** [comment]
点什么

**Comment by Blindingend** [comment]
第一周感觉自己效率不太行。做了总体设计，但是有考虑不周的地方，然后就是熟悉了一下wepy的使用，做了两个组件，一个user页面。考验了几次阿锋。周末打算完善一下设计demo，把之前没考虑的地方加上去。
