### ISSUE TITLE
第二周工作总结

### ISSUE THREAD

**Issue by Veiasai** [Veiasai/Xmap#3]
迭代即将结束，小学期过半。
大家再接再厉。

**Comment by GIRVANAL** [comment]
这一周自己还是不够自觉，基本做的都是上周修修补补的工作，查漏补缺。希望下一个迭代继续努力！

**Comment by Blindingend** [comment]
+1，这一周感觉做的很多都是零零碎碎的工作。接下来要好好努力提升自己，变得和阿锋一样牛逼。
