### ISSUE TITLE
新学习方向之Jmeter

### ISSUE THREAD

**Issue by Veiasai** [Veiasai/Xmap#4]
说说看法和学习进度。

**Comment by Veiasai** [comment]
计划将Jmeter用于性能测试。

**Comment by GIRVANAL** [comment]
Jmeter是强大的开源测试工具，感觉前几天接触一下之后，用于后端接口的自动化性能测试非常方便，准备在暑假进行更加深入的学习。

**Comment by Veiasai** [comment]
单机短消息请求，一百个线程都会导致peer reset，需要多台压力机。
