### ISSUE TITLE
第三周工作总结

### ISSUE THREAD

**Issue by Veiasai** [Veiasai/Xmap#6]
！！！
还有一周就回家啦！！！
任务都做完了吗！！

**Comment by Blindingend** [comment]
没有做完！！！
我还得等到八月中旬才能回家！！！
啊啊啊啊啊啊啊！！！！

**Comment by Blindingend** [comment]
这周的前两天在调小程序端的UI，使得迭代1的UI基本完成（当然现在又被毁了）
后面几天在做web端，感受到了自己之前react学艺不精所带来的遗留问题，以后学东西还是要多多深入，不能不求甚解
