### ISSUE TITLE
第四周工作总结、小学期完结感言

### ISSUE THREAD

**Issue by Veiasai** [Veiasai/Xmap#9]
！！！
回家。

**Comment by Blindingend** [comment]
**感谢阿锋，感谢阿文，愿意带上菜菜的我一起飞。很舍不得大家，和大家一起吹逼很开心。期待暑假在 issue 上还能见到大家！**

**Comment by GIRVANAL** [comment]
感谢阿锋，感谢阿嫣，愿意带上菜菜的我一起飞。很舍不得大家，和大家一起吹逼很开心。期待暑假在 issue 上还能见到大家！

**Comment by Veiasai** [comment]
感谢阿文，感谢阿嫣，愿意带上菜菜的我一起飞。很舍不得大家，和大家一起吹逼很开心。期待暑假在 issue 上还能见到大家！
